### ISSUE TITLE
[Request] Support `querySnapshot.metadata.hasPendingWrites`

### ISSUE THREAD

**Issue by mesqueeb** [mikkopaderes/mock-cloud-firestore#57]
I'd love support for `querySnapshot.metadata.hasPendingWrites` inside `onSnapshot`
```js
dbRef.onSnapshot(querySnapshot => {
  // querySnapshot.metadata.hasPendingWrites
})
```

#46

**Comment by rmmmp** [comment]
This is the part where it gets tricky for the mock. That is to track changes for the `onSnapshot` and emulate those APIs accurately. That's why I haven't implemented too much on the these section when I started this project.

I don't think I'll be able to work on this for a while so if anyone wants to take a stab at this change feel free to do so.

**Comment by mesqueeb** [comment]
Can I try to make it so it just runs once for all documents already inside fixtureData?

**Comment by rmmmp** [comment]
What would happen if someone has the `isNaiveSnapshotListenerEnabled` option set to true?

**Comment by mesqueeb** [comment]
@rmmmp I haven't started coding yet XD but I know i'd need to make it in a non-breaking way! 

How does the current isNaiveSnapshotListenerEnabled work? There wasn't much documentation on it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
